# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWISH-HiLiter
version:      0.04
version_from: HiLiter.pm
installdirs:  site
requires:
    HTML::HiLiter:                 0.11
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
